version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: prisma
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: prisma
    steps:
      - checkout
      - run: sudo apt install postgresql-client
      - run: yarn
      - run:
          name: Waiting for PostgreSQL to start
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Wait for MySQL to start
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: test
          command: |
            yarn build
            yarn build:runtime
            yarn test
            yarn coverage
          environment:
            PRISMA_GENERATE: true
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: prisma
            MYSQL_ROOT_PASSWORD: prisma
  publish:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Release packages
          command: yarn release

workflows:
  version: 2
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: main
